name: Python Calculater Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

##giving permission to github actions to read the content of repo
permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    ##our project should be compatiable with ubuntu and windws
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:
        pip install -r requirements.txt